version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_bot_app
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env.example
